from __future__ import annotations

# Base officielle demandée + champs enrichis pour scoring futur.
provider_capabilities: dict[str, dict[str, object]] = {
    "groq": {
        "provider": "groq",
        "model": "llama-3.1-8b-instant",
        "tier": "economic",
        "strength": ["speed", "low_cost", "fast_text"],
        "estimated_cost_per_1k_tokens_usd": 0.04,
        "priority": 115,
        "max_context_tokens": 128000,
        "reasoning_score": 68,
        "availability": "primary",
        "enterprise_sovereign_ready": False,
        "task_profiles": ["simple", "volume", "fast"],
    },
    "mistral": {
        "provider": "mistral",
        "model": "mistral-small-latest",
        "tier": "economic",
        "strength": ["speed", "low_cost", "european"],
        "estimated_cost_per_1k_tokens_usd": 0.10,
        "priority": 92,
        "max_context_tokens": 128000,
        "reasoning_score": 74,
        "availability": "secondary",
        "enterprise_sovereign_ready": False,
        "task_profiles": ["simple", "volume"],
    },
    "deepseek_flash": {
        "provider": "deepseek",
        "model": "deepseek-v4-flash",
        "tier": "economic",
        "strength": ["speed", "low_cost"],
        "estimated_cost_per_1k_tokens_usd": 0.08,
        "priority": 100,
        "max_context_tokens": 128000,
        "reasoning_score": 62,
        "availability": "primary",
        "enterprise_sovereign_ready": False,
        "task_profiles": ["simple", "volume"],
    },
    "deepseek_pro": {
        "provider": "deepseek",
        "model": "deepseek-v4-pro",
        "tier": "reasoning",
        "strength": ["reasoning", "analysis"],
        "estimated_cost_per_1k_tokens_usd": 0.28,
        "priority": 95,
        "max_context_tokens": 128000,
        "reasoning_score": 86,
        "availability": "primary",
        "enterprise_sovereign_ready": False,
        "task_profiles": ["reasoning", "analysis"],
    },
    "kimi": {
        "provider": "kimi",
        "model": "kimi-k2-0905-preview",
        "tier": "agent",
        "strength": ["long_context", "memory"],
        "estimated_cost_per_1k_tokens_usd": 0.22,
        "priority": 88,
        "max_context_tokens": 200000,
        "reasoning_score": 84,
        "availability": "secondary",
        "enterprise_sovereign_ready": False,
        "task_profiles": ["long_context", "agentic", "memory"],
    },
    "openai": {
        "provider": "openai",
        "model": "gpt-4o-mini",
        "tier": "elite",
        "strength": ["premium_reasoning", "tools", "quality"],
        "estimated_cost_per_1k_tokens_usd": 0.35,
        "priority": 80,
        "max_context_tokens": 128000,
        "reasoning_score": 90,
        "availability": "secondary",
        "enterprise_sovereign_ready": False,
        "task_profiles": ["premium_tools", "complex", "reasoning"],
    },
    "infomaniak": {
        "provider": "infomaniak",
        "model": "",
        "tier": "sovereign_eu",
        "strength": ["eu_compliance", "privacy", "enterprise"],
        "estimated_cost_per_1k_tokens_usd": 0.30,
        "priority": 78,
        "max_context_tokens": 64000,
        "reasoning_score": 75,
        "availability": "european_layer",
        "enterprise_sovereign_ready": True,
        "task_profiles": ["enterprise_sovereign", "compliance", "rgpd"],
    },
}

